# This task merges all the configuration fragments into one file
- name: Apply configuration
  hosts: aggregation
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Pushing config ... please wait
      junos_install_config: >
        host={{ inventory_hostname }}
        port={{ PLATFORM.netconf_port }}
        user=root
        passwd=Embe1mpls
        file={{ jfd_conf }}
        overwrite=yes
        logfile=/tmp/build/changes.log
