
validate:
    main:
        global:  { type: dict, validate: global, mandatory: 1  }
        vlans:   { type: dict, validate: vlans, mandatory: 1  }
    global:
        default_gw_ip:  { type: integer, default: 1  }
        router_ips:     { type: list, mandatory: 1 }
        base_mac_addr:  { type: string, mandatory: 0, default: '00:11:22:33:44:'} # Add Regex to validate format
        mc_lag_mode:    { type: string, mandatory: 0, default: 'active-active', values: ['active-active', 'active-passive'] }
        iccp_vlan_name: { type: string, mandatory: 0, default: 'ICCP_VLAN' }
        iccp_vlan_id:   { type: integer, mandatory: 0, default: 1 }
        icl_interface:  { type: string, mandatory: 0, default: 'ae0' }
        gen_file_name:  { type: string, mandatory: 0, default: 'generated_by_babel2.yml' }


    vlans:
        '*':     { type: dict, validate: vlan_entry }
    vlan_entry:
        id:             { type: integer, mandatory: 1 }
        description:    { type: string, default: "missing description" }
        network:        { type: string, mandatory: 1 }
        links:          { type: list }
